#!/bin/bash

# This bash script adds 2 files to IPFS and stores their hashes
# in the same folder as the files. It also appends those hashes
# to a master index of hashes which is also saved in IPFS by
# the python3 program that calls this script.
#
# args: $1 == path to group containing folders holding videos
#       $2 == group (youtube channel) this video belongs to
#       $3 == base file name for all associated files
#       $4 == extention for the video file
#echo $0 $1 $2 $3 $4

cd $1
ipfs add "$3.info.json" > metaHash.txt 2> /dev/null
ipfs add "$3$4" > videoHash.txt 2> /dev/null

cat metaHash.txt >> ../groupHashes.txt 2> /dev/null
cat videoHash.txt >> ../groupHashes.txt 2> /dev/null




